### ISSUE TITLE
filename.js and filename.min.js causing duplicate (and failing) deletes

### ISSUE THREAD

**Issue by pwmckenna** [techjacker/node-version-assets#10]
My project sets the contents of the [mediaelement build folder](https://github.com/johndyer/mediaelement/tree/master/build) as the assets (each file is individually specified due to grunt wildcard filename matching). I get unlink errors from this call: https://github.com/techjacker/node-version-assets/blob/master/lib/create.js#L66

it appears to fail when trying to delete any .min file that has a corresponding unminified file that is also part of the asset array.

options: no options other than `assets` and `grepFiles` are specified

**Comment by techjacker** [comment]
V1 fixed a lot of bugs. Can you retest with a 1+ version and let me know if the bug still occurs?

**Comment by techjacker** [comment]
Assuming this is no longer an issue.
