### ISSUE TITLE
How to use this as package.json script?

### ISSUE THREAD

**Issue by marekdon** [techjacker/node-version-assets#19]
Is it possible to use it as package.json script or it is a Grunt task?

**Comment by techjacker** [comment]
Yes you could it's just not a one liner:
https://github.com/techjacker/node-version-assets#input-options-in-script

I'd suggest putting that code in a standalone file, eg `build.js` and running that from the package.json,  eg:
```
{ "scripts" :
  { "build": "node build.js"}
}
```
